In [10]:
import pandas as pd

url = "https://nc-aftermarket-www-production.s3.amazonaws.com/reports/Namecheap_Market_Sales.csv"

df = pd.read_csv(url)

In [11]:
df.head()

,url,name,startDate,endDate,price,startPrice,renewPrice,bidCount,ahrefsDomainRating,alexaRanking,umbrellaRanking,backlinksCount,cloudflareRanking,estibotValue,extensionsTaken,keywordSearchCount,keywordSearchQuery,registeredDate,lastSoldPrice,lastSoldYear
0,https://www.namecheap.com/market/sale/xgXPCMcF...,bitcoin.contractors,2024-03-15T23:30:00.000Z,2024-03-31T16:00:00.000Z,15.0,15,31.98,0,0,NaN,NaN,0,NaN,0,472,3377580,"bitcoin,contractors",2014-02-21T00:00:00.000Z,0,NaN
1,https://www.namecheap.com/market/sale/abdZTtAo...,nft.vet,2024-03-13T23:30:00.000Z,2024-03-29T16:00:00.000Z,15.0,15,35.98,0,0,NaN,NaN,0,NaN,5,468,0,"n,f,t,vet",2021-02-19T00:00:00.000Z,0,NaN
2,https://www.namecheap.com/market/sale/tFH35tkN...,ian.xyz,2024-03-09T23:30:00.000Z,2024-03-25T16:00:00.000Z,15.0,15,1300.00,0,0,NaN,NaN,0,NaN,55,154,2250900,ian,2017-02-15T00:00:00.000Z,0,NaN
3,https://www.namecheap.com/market/sale/u1kZEchX...,iwin.fun,2024-03-11T23:30:00.000Z,2024-03-27T16:00:00.000Z,15.0,15,32.50,0,28,NaN,NaN,0,NaN,75,414,0,"iwin,fun",2021-02-17T00:00:00.000Z,0,NaN
4,https://www.namecheap.com/market/sale/uUFWB9Yo...,with.fund,2024-03-14T23:30:00.000Z,2024-03-30T16:00:00.000Z,15.0,15,54.98,0,7,NaN,NaN,3,NaN,1600,360,25092000,"with,fund",2017-02-20T00:00:00.000Z,0,NaN

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345703 entries, 0 to 345702
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   url                 345703 non-null  object
 1   name                345703 non-null  object
 2   startDate           345703 non-null  object
 3   endDate             345703 non-null  object
 4   price               345703 non-null  float64
 5   startPrice          345703 non-null  int64
 6   renewPrice          345703 non-null  float64
 7   bidCount            345703 non-null  int64
 8   ahrefsDomainRating  345703 non-null  int64
 9   alexaRanking        0 non-null       float64
 10  umbrellaRanking     0 non-null       float64
 11  backlinksCount      345703 non-null  int64
 12  cloudflareRanking   320 non-null     float64
 13  estibotValue        345703 non-null  int64
 14  extensionsTaken     345703 non-null  int64
 15  keywordSearchCount  345703 non-null  int64
 16  keywordSearchQuery  345428 non-null  object
 17  registeredDate      340277 non-null  object
 18  lastSoldPrice       345703 non-null  int64
 19  lastSoldYear        1404 non-null    float64
dtypes: float64(6), int64(8), object(6)
memory usage: 52.8+ MB