In [ ]:
import pandas as pd

In [14]:
# Replace with your actual file path
file_path = "/Users/adamsmart/Library/CloudStorage/OneDrive-Personal/Data/projects/birth_data/Nat2022PublicUS.c20230504.r20230822.txt"
# For CSV files
df = pd.read_csv(file_path)

In [15]:
df.head()

  202201    12187        21                2                        37116    1                   101101  0  011 X1  16 1                    400701101   00115 1     000000  1  1               88888   88888   88888     0713          10  061      N10000000000001111N1         67125.83    1651   999 19991     NNNNNN111111NXX111N00 111     NNNNN111111      NN 11                  NNNNNN1111111     11X111111     NNNNN 11111 1     4N2211     1041885   1    9               F 03  2021     42102    410923203 073     NNNNNN 111111 1     NNNNNN111111NNNNNN1111111     NYY1
0          202201    15257        31             ...
1          202201    05392        31             ...
2          202201    01226        31             ...
3          202201    18011        11             ...
4          202201    04481        11             ...

In [16]:
print(df.head(10))

  202201    12187        21                2                        37116    1                   101101  0  011 X1  16 1                    400701101   00115 1     000000  1  1               88888   88888   88888     0713          10  061      N10000000000001111N1         67125.83    1651   999 19991     NNNNNN111111NXX111N00 111     NNNNN111111      NN 11                  NNNNNN1111111     11X111111     NNNNN 11111 1     4N2211     1041885   1    9               F 03  2021     42102    410923203 073     NNNNNN 111111 1     NNNNNN111111NNNNNN1111111     NYY1
0          202201    15257        31             ...
1          202201    05392        31             ...
2          202201    01226        31             ...
3          202201    18011        11             ...
4          202201    04481        11             ...
5          202201    08542        11             ...
6          202201    08327        11             ...
7          202201    13403        11             ...
8          202201    05292        11             ...
9          202201    03523        11             ...

In [17]:
##import pandas as pd

# =============================================================================
# Complete column specifications and column names based on the data dictionary.
# Non‐filler fields only. (Positions given in the dictionary are 1-indexed;
# we convert to 0-indexed for Python.)
#
# For clarity, comments show the dictionary field name, positions, and a brief
# description. (You can extend or modify as needed.)
# =============================================================================

colspecs = [
    (8, 12),    # DOB YY (Birth Year) – positions 9-12
    (12, 14),   # DOB MM (Birth Month) – positions 13-14
    (18, 22),   # DOB TT (Time of Birth) – positions 19-22
    (22, 23),   # DOB WK (Birth Day of Week) – position 23
    (31, 32),   # BFACIL (Birth Place) – position 32
    (32, 33),   # BFACIL Reporting Flag – position 33
    (49, 50),   # BFACIL3 (Birth Place Recode) – position 50
    (72, 73),   # MAGE IMPFLG (Mother’s Age Imputed Flag) – position 73
    (73, 74),   # MAGE REPFLG (Reported Age of Mother Used Flag) – position 74
    (74, 76),   # MAGER (Mother’s Single Years of Age) – positions 75-76
    (76, 78),   # MAGER14 (Mother’s Age Recode 14) – positions 77-78
    (78, 79),   # MAGER9 (Mother’s Age Recode 9) – position 79
    (83, 84),   # MBSTATE (Mother’s Nativity) – position 84
    (103, 104), # RESTATUS (Residence Status) – position 104
    (104, 106), # MRACE31 (Mother’s Race Recode 31) – positions 105-106
    (106, 108), # MRACE6 (Mother’s Race Recode 6) – position 107 (2 characters)
    (107, 109), # MRACE15 (Mother’s Race Recode 15) – positions 108-109
    (110, 111), # MRACEIMP (Mother’s Race Imputed Flag) – position 111
    (111, 112), # MHISPX (Mother’s Hispanic Origin) – position 112
    (114, 115), # MHISP_R (Mother’s Hispanic Origin Recode) – position 115
    (115, 116), # MHISP Reporting Flag – position 116
    (116, 117), # MRACEHISP (Mother’s Race/Hispanic Origin) – position 117
    (118, 119), # MAR (Paternity Acknowledged) – position 119
    (119, 120), # DMAR (Marital Status) – position 120
    (120, 121), # MAR_IMP (Mother’s Marital Status Imputed) – position 121
    (122, 123), # P Reporting Flag for Paternity – position 123
    (123, 124), # MEDUC (Mother’s Education) – position 124
    (125, 126), # MEDUC Reporting Flag for Mother – position 126
    # --- Father’s characteristics ---
    (141, 142), # FAGERPT (Father’s Reported Age Used Flag) – position 142
    (146, 148), # FAGECOMB (Father’s Combined Age) – positions 147-148
    (148, 150), # FAGEREC11 (Father’s Age Recode 11) – positions 149-150
    (150, 152), # FRACE31 (Father’s Race Recode 31) – positions 151-152
    (152, 153), # FRACE6 (Father’s Race Recode 6) – position 153
    (153, 155), # FRACE15 (Father’s Race Recode 15) – positions 154-155
    (158, 159), # FHISPX (Father’s Hispanic Origin) – position 159
    (159, 160), # FHISP_R (Father’s Hispanic Origin Recode) – position 160
    (160, 161), # FHISP Reporting Flag – position 161
    (161, 162), # FRACEHISP (Father’s Race/Hispanic Origin) – position 162
    (162, 163), # FEDUC (Father’s Education) – position 163
    (164, 165), # FEDUC Reporting Flag for Father – position 165
    # --- Prior births ---
    (170, 172), # PRIORLIVE (Prior Births Now Living) – positions 171-172
    (172, 174), # PRIORDEAD (Prior Births Now Dead) – positions 173-174
    (174, 176), # PRIORTERM (Prior Other Terminations) – positions 175-176
    (178, 179), # LBO (Live Birth Order Recode) – position 179
    (181, 182), # TBO (Total Birth Order Recode) – position 182
    (197, 200), # ILLB (Interval Since Last Live Birth Recode) – positions 198-200
    (200, 202), # ILLB_R11 (Interval Since Last Live Birth Recode 11) – positions 201-202
    (205, 208), # ILOP (Interval Since Last Other Pregnancy Recode) – positions 206-208
    (208, 210), # ILOP_R11 (Interval Since Last Other Pregnancy Recode 11) – positions 209-210
    (213, 216), # ILP (Interval Since Last Pregnancy Recode) – positions 214-216
    (216, 218), # ILP_R11 (Interval Since Last Pregnancy Recode 11) – positions 217-218
    # --- Prenatal care ---
    (223, 225), # PRECARE (Prenatal Care Began) – positions 224-225
    (225, 226), # MPCB Reporting Flag for Prenatal Care Began – position 226
    (226, 227), # PRECARE5 (Prenatal Care Began Recode) – position 227
    (237, 239), # PREVIS (Number of Prenatal Visits) – positions 238-239
    (241, 243), # PREVIS_R (Prenatal Visits Recode) – positions 242-243
    (243, 244), # TPCV Reporting Flag for Total Prenatal Care Visits – position 244
    # --- WIC & Smoking ---
    (250, 251), # WIC – position 251
    (251, 252), # WIC Reporting Flag – position 252
    (252, 254), # CIG0 (Cigarettes Before Pregnancy) – positions 253-254
    (254, 256), # CIG1 (Cigarettes 1st Trimester) – positions 255-256
    (256, 258), # CIG2 (Cigarettes 2nd Trimester) – positions 257-258
    (258, 260), # CIG3 (Cigarettes 3rd Trimester) – positions 259-260
    (260, 261), # CIG_REC (Cigarettes Before Pregnancy Recode) – position 261
    (261, 262), # CIG1_REC (Cigarettes 1st Trimester Recode) – position 262
    (262, 263), # CIG2_REC (Cigarettes 2nd Trimester Recode) – position 263
    (263, 264), # CIG3_REC (Cigarettes 3rd Trimester Recode) – position 264
    (264, 265), # CIGS Reporting Flag for Cigarettes Before Pregnancy – position 265
    (265, 266), # CIGS Reporting Flag for Cigarettes 1st Trimester – position 266
    (266, 267), # CIGS Reporting Flag for Cigarettes 2nd Trimester – position 267
    (267, 268), # CIGS Reporting Flag for Cigarettes 3rd Trimester – position 268
    (268, 269), # CIG_REC2 (Cigarette Recode Overall) – position 269
    (269, 270), # TOBACO Reporting Flag for Tobacco use – position 270
    # --- Maternal Anthropometrics ---
    (279, 281), # Mht (Mother’s Height in inches) – positions 280-281
    (281, 282), # MHT Reporting Flag for Mother’s Height – position 282
    (282, 286), # BMI (Body Mass Index) – positions 283-286
    (286, 287), # BMI_RECODE – position 287
    (291, 294), # PWgt (Pre-pregnancy Weight) – positions 292-294
    (294, 295), # PWGT Reporting Flag – position 295
    (298, 301), # DWgt (Delivery Weight) – positions 299-301
    (302, 303), # DWGT Reporting Flag – position 303
    (303, 305), # WTGAIN (Weight Gain) – positions 304-305
    (305, 306), # WTGAIN_RECODE – position 306
    (306, 307), # WTGAIN Reporting Flag – position 307
    # --- Risk Factors, Infections, and Procedures ---
    (312, 342), # Risk Factors – positions 313-342 (30 characters)
    (342, 358), # Infections Present – positions 343-358 (15 characters)
    (358, 370), # Obstetric Procedures – positions 359-370 (12 characters)
    # --- Characteristics of Labor and Delivery ---
    (382, 400), # Characteristics of Labor and Delivery – positions 383-400 (18 characters)
    (400, 414), # Method of Delivery – positions 401-414 (14 characters)
    (414, 432), # Maternal Morbidity – positions 415-432 (18 characters)
    (432, 433), # ATTEND (Attendant at Birth) – position 433
    (433, 434), # MTRAN (Mother Transferred) – position 434
    (434, 435), # PAY (Payment Source for Delivery) – position 435
    (435, 436), # PAY_RECODE (Payment Recode) – position 436
    (436, 437), # PAY Reporting Flag – position 437
    # --- Apgar Scores & Plurality ---
    (443, 445), # APGAR5 (Five Minute APGAR Score) – positions 444-445
    (445, 446), # APGAR5_RECODE (Five Minute APGAR Recode) – position 446
    (446, 447), # APGAR5 Reporting Flag – position 447
    (447, 449), # APGAR10 (Ten Minute APGAR Score) – positions 448-449
    (449, 450), # APGAR10_RECODE (Ten Minute APGAR Recode) – position 450
    (453, 454), # DPLURAL (Plurality Recode) – position 454
    (455, 456), # PLUR (Plurality Imputed) – position 456
    (458, 459), # SETORDER (Set Order Recode) – position 459
    # --- Infant Information ---
    (474, 475), # SEX (Sex of Infant) – position 475
    (475, 476), # SEX_IMP (Sex Imputed) – position 476
    (476, 478), # DLMP_MM (Last Normal Menses Month) – positions 477-478
    (480, 484), # DLMP_YY (Last Normal Menses Year) – positions 481-484
    (485, 486), # COMPGST (Combined Gestation Imputation Flag) – position 485
    (486, 487), # OBGEST (Obstetric Estimate Used Flag) – position 486
    (489, 491), # COMBGEST (Combined Gestation – Detail in Weeks) – positions 490-491
    (491, 493), # GESTREC10 (Combined Gestation Recode 10) – positions 492-493
    (493, 494), # GESTREC3 (Combined Gestation Recode 3) – position 494
    (497, 498), # LMPUSED (Combined Gestation Used Flag) – position 498
    (498, 500), # OEGest (Obstetric Estimate Edited) – positions 499-500
    (500, 502), # OEGest_R10 (Obstetric Estimate Recode10) – positions 501-502
    (502, 503), # OEGest_R3 (Obstetric Estimate Recode 3) – position 503
    (503, 507), # DBWT (Birth Weight – Detail in Grams) – positions 504-507
    (507, 510), # BWTR12 (Birth Weight Recode 12) – positions 509-510
    (510, 511), # BWTR4 (Birth Weight Recode 4) – position 511
    # --- Abnormal Conditions & Congenital Anomalies ---
    (516, 536), # Abnormal Conditions of the Newborn – positions 517-536 (20 characters)
    (536, 566), # Congenital Anomalies of the Newborn – positions 537-566 (30 characters)
    # --- Final Infant Fields ---
    (566, 567), # ITRAN (Infant Transferred) – position 567
    (567, 568), # ILIVE (Infant Living at Time of Report) – position 568
    (568, 569), # BFED (Infant Breastfed at Discharge) – position 569
    (569, 570)  # BFED Reporting Flag – position 570
]

column_names = [
    "birth_year",
    "birth_month",
    "time_of_birth",
    "birth_day_of_week",
    "birth_place",
    "birth_place_reporting_flag",
    "birth_place_recode",
    "mother_age_imputed_flag",
    "mother_reported_age_flag",
    "mother_age",
    "mother_age_recode14",
    "mother_age_recode9",
    "mother_nativity",
    "residence_status",
    "mother_race_recode31",
    "mother_race_recode6",
    "mother_race_recode15",
    "mother_race_imputed_flag",
    "mother_hispanic_origin",
    "mother_hispanic_origin_recode",
    "mother_hispanic_reporting_flag",
    "mother_race_hispanic",
    "paternity_acknowledged",
    "marital_status",
    "mother_marital_status_imputed",
    "paternity_reporting_flag",
    "mother_education",
    "mother_education_reporting_flag",
    # --- Father’s characteristics ---
    "father_age_used_flag",
    "father_combined_age",
    "father_age_recode11",
    "father_race_recode31",
    "father_race_recode6",
    "father_race_recode15",
    "father_hispanic_origin",
    "father_hispanic_origin_recode",
    "father_hispanic_reporting_flag",
    "father_race_hispanic",
    "father_education",
    "father_education_reporting_flag",
    # --- Prior births ---
    "prior_births_now_living",
    "prior_births_now_dead",
    "prior_other_terminations",
    "live_birth_order_recode",
    "total_birth_order_recode",
    "interval_since_last_live_birth_recode",
    "interval_since_last_live_birth_recode11",
    "interval_since_last_other_pregnancy_recode",
    "interval_since_last_other_pregnancy_recode11",
    "interval_since_last_pregnancy_recode",
    "interval_since_last_pregnancy_recode11",
    # --- Prenatal care ---
    "prenatal_care_began",
    "prenatal_care_reporting_flag",
    "prenatal_care_recode",
    "num_prenatal_visits",
    "prenatal_visits_recode",
    "total_prenatal_visits_reporting_flag",
    # --- WIC & Smoking ---
    "wic",
    "wic_reporting_flag",
    "cigarettes_before_pregnancy",
    "cigarettes_1st_trimester",
    "cigarettes_2nd_trimester",
    "cigarettes_3rd_trimester",
    "cigarette_recode_before_pregnancy",
    "cigarette_recode_1st_trimester",
    "cigarette_recode_2nd_trimester",
    "cigarette_recode_3rd_trimester",
    "cigarettes_before_pregnancy_reporting_flag",
    "cigarettes_1st_trimester_reporting_flag",
    "cigarettes_2nd_trimester_reporting_flag",
    "cigarettes_3rd_trimester_reporting_flag",
    "cigarette_recode_overall",
    "tobacco_reporting_flag",
    # --- Maternal Anthropometrics ---
    "mother_height",
    "mother_height_reporting_flag",
    "body_mass_index",
    "bmi_recode",
    "pre_pregnancy_weight",
    "pre_pregnancy_weight_reporting_flag",
    "delivery_weight",
    "delivery_weight_reporting_flag",
    "weight_gain",
    "weight_gain_recode",
    "weight_gain_reporting_flag",
    # --- Risk Factors, Infections, and Procedures ---
    "risk_factors",
    "infections_present",
    "obstetric_procedures",
    # --- Characteristics of Labor and Delivery ---
    "characteristics_of_labor_and_delivery",
    "method_of_delivery",
    "maternal_morbidity",
    "attendant_at_birth",
    "mother_transferred",
    "payment_source",
    "payment_recode",
    "payment_reporting_flag",
    # --- Apgar Scores & Plurality ---
    "apgar5",
    "apgar5_recode",
    "apgar5_reporting_flag",
    "apgar10",
    "apgar10_recode",
    "plurality_recode",
    "plurality_imputed",
    "set_order_recode",
    # --- Infant Information ---
    "sex",
    "sex_imputed",
    "dlmp_month",
    "dlmp_year",
    "comp_gest_imputation_flag",
    "obstetric_estimate_used_flag",
    "combined_gestation_weeks",
    "combined_gestation_recode10",
    "combined_gestation_recode3",
    "lmp_used",
    "obstetric_estimate_edited",
    "obstetric_estimate_recode10",
    "obstetric_estimate_recode3",
    "birth_weight_detail",
    "birth_weight_recode12",
    "birth_weight_recode4",
    # --- Abnormal Conditions & Congenital Anomalies ---
    "abnormal_conditions_newborn",
    "congenital_anomalies_newborn",
    # --- Final Infant Fields ---
    "infant_transferred",
    "infant_living",
    "infant_breastfed",
    "infant_breastfed_reporting_flag"
]

# =============================================================================
# Read the fixed-width file using pandas
# (Update the file path as needed. If the file is compressed or in a zip,
# you may need to extract or use an appropriate method.)
# =============================================================================

##file_path = "path/to/your/datafile.txt"  # <-- Replace with your actual file path

df = pd.read_fwf(file_path, colspecs=colspecs, names=column_names)

# =============================================================================
# Display the first few rows of the DataFrame
# =============================================================================

print(df.head(10))

   birth_year  birth_month  time_of_birth  birth_day_of_week  birth_place  \
0        2022            1           1218                  7            2
1        2022            1           1525                  7            3
2        2022            1            539                  2            3
3        2022            1            122                  6            3
4        2022            1           1801                  1            1
5        2022            1            448                  1            1
6        2022            1            854                  2            1
7        2022            1            832                  7            1
8        2022            1           1340                  3            1
9        2022            1            529                  2            1

   birth_place_reporting_flag  birth_place_recode  mother_age_imputed_flag  \
0                           1                   2                      NaN
1                           1                   2                      NaN
2                           1                   2                      NaN
3                           1                   2                      NaN
4                           1                   1                      NaN
5                           1                   1                      NaN
6                           1                   1                      NaN
7                           1                   1                      NaN
8                           1                   1                      NaN
9                           1                   1                      NaN

   mother_reported_age_flag  mother_age  ...  obstetric_estimate_recode3  \
0                       NaN          37  ...                           2
1                       NaN          27  ...                           2
2                       NaN          25  ...                           2
3                       NaN          42  ...                           2
4                       NaN          27  ...                           2
5                       NaN          22  ...                           2
6                       NaN          35  ...                           2
7                       NaN          20  ...                           2
8                       NaN          37  ...                           2
9                       NaN          37  ...                           1

   birth_weight_detail  birth_weight_recode12  birth_weight_recode4  \
0                 3203                      7                     3
1                 3090                      7                     3
2                 2523                      6                     3
3                 4139                      9                     3
4                 3000                      7                     3
5                 3540                      8                     3
6                 4450                      9                     3
7                 3630                      8                     3
8                 2800                      6                     3
9                 2615                      6                     3

   abnormal_conditions_newborn  congenital_anomalies_newborn  \
0              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
1              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
2              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
3              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
4              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
5              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
6              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
7              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
8              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
9              YNYNYN 111111 0     NNNNNN111111NNNNNN1111111

   infant_transferred  infant_living  infant_breastfed  \
0                   N              Y                 Y
1                   N              Y                 Y
2                   N              Y                 Y
3                   N              Y                 Y
4                   N              Y                 Y
5                   N              Y                 Y
6                   N              Y                 Y
7                   N              Y                 Y
8                   N              Y                 Y
9                   N              Y                 N

   infant_breastfed_reporting_flag
0                                1
1                                1
2                                1
3                                1
4                                1
5                                1
6                                1
7                                1
8                                1
9                                1

[10 rows x 125 columns]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3676029 entries, 0 to 3676028
Columns: 125 entries, birth_year to infant_breastfed_reporting_flag
dtypes: float64(12), int64(97), object(16)
memory usage: 3.4+ GB

In [19]:
print(df.head(10))

   birth_year  birth_month  time_of_birth  birth_day_of_week  birth_place  \
0        2022            1           1218                  7            2
1        2022            1           1525                  7            3
2        2022            1            539                  2            3
3        2022            1            122                  6            3
4        2022            1           1801                  1            1
5        2022            1            448                  1            1
6        2022            1            854                  2            1
7        2022            1            832                  7            1
8        2022            1           1340                  3            1
9        2022            1            529                  2            1

   birth_place_reporting_flag  birth_place_recode  mother_age_imputed_flag  \
0                           1                   2                      NaN
1                           1                   2                      NaN
2                           1                   2                      NaN
3                           1                   2                      NaN
4                           1                   1                      NaN
5                           1                   1                      NaN
6                           1                   1                      NaN
7                           1                   1                      NaN
8                           1                   1                      NaN
9                           1                   1                      NaN

   mother_reported_age_flag  mother_age  ...  obstetric_estimate_recode3  \
0                       NaN          37  ...                           2
1                       NaN          27  ...                           2
2                       NaN          25  ...                           2
3                       NaN          42  ...                           2
4                       NaN          27  ...                           2
5                       NaN          22  ...                           2
6                       NaN          35  ...                           2
7                       NaN          20  ...                           2
8                       NaN          37  ...                           2
9                       NaN          37  ...                           1

   birth_weight_detail  birth_weight_recode12  birth_weight_recode4  \
0                 3203                      7                     3
1                 3090                      7                     3
2                 2523                      6                     3
3                 4139                      9                     3
4                 3000                      7                     3
5                 3540                      8                     3
6                 4450                      9                     3
7                 3630                      8                     3
8                 2800                      6                     3
9                 2615                      6                     3

   abnormal_conditions_newborn  congenital_anomalies_newborn  \
0              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
1              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
2              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
3              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
4              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
5              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
6              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
7              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
8              NNNNNN 111111 1     NNNNNN111111NNNNNN1111111
9              YNYNYN 111111 0     NNNNNN111111NNNNNN1111111

   infant_transferred  infant_living  infant_breastfed  \
0                   N              Y                 Y
1                   N              Y                 Y
2                   N              Y                 Y
3                   N              Y                 Y
4                   N              Y                 Y
5                   N              Y                 Y
6                   N              Y                 Y
7                   N              Y                 Y
8                   N              Y                 Y
9                   N              Y                 N

   infant_breastfed_reporting_flag
0                                1
1                                1
2                                1
3                                1
4                                1
5                                1
6                                1
7                                1
8                                1
9                                1

[10 rows x 125 columns]

In [22]:
print(df.columns.tolist())

['birth_year', 'birth_month', 'time_of_birth', 'birth_day_of_week', 'birth_place', 'birth_place_reporting_flag', 'birth_place_recode', 'mother_age_imputed_flag', 'mother_reported_age_flag', 'mother_age', 'mother_age_recode14', 'mother_age_recode9', 'mother_nativity', 'residence_status', 'mother_race_recode31', 'mother_race_recode6', 'mother_race_recode15', 'mother_race_imputed_flag', 'mother_hispanic_origin', 'mother_hispanic_origin_recode', 'mother_hispanic_reporting_flag', 'mother_race_hispanic', 'paternity_acknowledged', 'marital_status', 'mother_marital_status_imputed', 'paternity_reporting_flag', 'mother_education', 'mother_education_reporting_flag', 'father_age_used_flag', 'father_combined_age', 'father_age_recode11', 'father_race_recode31', 'father_race_recode6', 'father_race_recode15', 'father_hispanic_origin', 'father_hispanic_origin_recode', 'father_hispanic_reporting_flag', 'father_race_hispanic', 'father_education', 'father_education_reporting_flag', 'prior_births_now_living', 'prior_births_now_dead', 'prior_other_terminations', 'live_birth_order_recode', 'total_birth_order_recode', 'interval_since_last_live_birth_recode', 'interval_since_last_live_birth_recode11', 'interval_since_last_other_pregnancy_recode', 'interval_since_last_other_pregnancy_recode11', 'interval_since_last_pregnancy_recode', 'interval_since_last_pregnancy_recode11', 'prenatal_care_began', 'prenatal_care_reporting_flag', 'prenatal_care_recode', 'num_prenatal_visits', 'prenatal_visits_recode', 'total_prenatal_visits_reporting_flag', 'wic', 'wic_reporting_flag', 'cigarettes_before_pregnancy', 'cigarettes_1st_trimester', 'cigarettes_2nd_trimester', 'cigarettes_3rd_trimester', 'cigarette_recode_before_pregnancy', 'cigarette_recode_1st_trimester', 'cigarette_recode_2nd_trimester', 'cigarette_recode_3rd_trimester', 'cigarettes_before_pregnancy_reporting_flag', 'cigarettes_1st_trimester_reporting_flag', 'cigarettes_2nd_trimester_reporting_flag', 'cigarettes_3rd_trimester_reporting_flag', 'cigarette_recode_overall', 'tobacco_reporting_flag', 'mother_height', 'mother_height_reporting_flag', 'body_mass_index', 'bmi_recode', 'pre_pregnancy_weight', 'pre_pregnancy_weight_reporting_flag', 'delivery_weight', 'delivery_weight_reporting_flag', 'weight_gain', 'weight_gain_recode', 'weight_gain_reporting_flag', 'risk_factors', 'infections_present', 'obstetric_procedures', 'characteristics_of_labor_and_delivery', 'method_of_delivery', 'maternal_morbidity', 'attendant_at_birth', 'mother_transferred', 'payment_source', 'payment_recode', 'payment_reporting_flag', 'apgar5', 'apgar5_recode', 'apgar5_reporting_flag', 'apgar10', 'apgar10_recode', 'plurality_recode', 'plurality_imputed', 'set_order_recode', 'sex', 'sex_imputed', 'dlmp_month', 'dlmp_year', 'comp_gest_imputation_flag', 'obstetric_estimate_used_flag', 'combined_gestation_weeks', 'combined_gestation_recode10', 'combined_gestation_recode3', 'lmp_used', 'obstetric_estimate_edited', 'obstetric_estimate_recode10', 'obstetric_estimate_recode3', 'birth_weight_detail', 'birth_weight_recode12', 'birth_weight_recode4', 'abnormal_conditions_newborn', 'congenital_anomalies_newborn', 'infant_transferred', 'infant_living', 'infant_breastfed', 'infant_breastfed_reporting_flag']